### ISSUE TITLE
v37 Weapon Issues

### ISSUE THREAD

**Issue by Hexopus** [NTrixner/RaggedLandsPenAndPaper#226]
After excel-ing for about 2-3hs, here are questions I stumbled across:

- Shouldn't **Slings & Slingshots** be in the category "throwing weapons"? Minor errors: you can learn "Trowing Training" and Short Spears are in the "thrown" category, instead of "throwing".
- To avoid confusion, I suggest using "You are trained with all (type) weapons" for normal trainings and "You are trained with ONE kind of weapon" for the **Weapon Training** perk. Also I am 90% certain there is a way to write "If you already have another perk..." only once, lol.
- Tough one here: Are **"Draw & Sheathe"** interesting design spaces? Is it fun to play around? Is it worth writing it down (and remembering) it for every single one, or shouldn't they just depend on weapon size for example (S= 2s, M=3s, L=4s)? With maybe exceptions for Daggers & Bows?
- Are **descriptors** like "Simple" and "Regular" necessary, if weapons already are collected in a list with that name? Are the "melee/ranged" descriptors used somewhere, and/or can they not reliably be concluded from the attack ranges?
- Speaking of which: Should the "one/two handed" descriptors be part of the weapon maneuvers?
- Is the ability to **knock out enemies** strictly a "blunt damage" thing, rather than a weapon type thing?
- Is there a fixed system behind cutting, blunt and piercing? Because it ain't **alphabetical**, lol.
- **Bearded Axe & Battle Axe** feel too similar. As do **Riding Bow & Bow.** I know it's a design document and there are things to be said for number of dice etc, but I'd rather have clearer niches than overwhelming options.
- "Has to be **reloaded** before every shot" makes it unclear whether a "re"load needs to happen before the first shot. Should it not be "loading"?
- "Reloading can be done as part of the shoot action" is equally confusing, as it sounds like the AP cost is covered, but I suppose it's more about the 1 action limitation per turn? Maybe use "in conjunction"? Or force it into one maneuver? 
- **Mace & Morning Star** have an odd damage calculation. Not only is the blunt damage missing, but the way rounding works in your system; 2x 1/2 ST is often more than ST. It's most likely not op tho, as it interacts unfavourably with armor, and carves this an interesting non-armor crushing niche.
- Are **Great Swords** and **Lances** supposed to be One-Handed? Is a Morning Star really a Two-Handed Mace? 
- Are **Guisarmes** not Polearms? Are **Hand Crossbows** their own "Hand Crossbow" category (as the descriptor implies) or Crossbows as well? Because the latter needs 710 CP to learn as an "unusual weapon", but only 110 CP as a package with all Crossbows.
- Sheet attached for your convenience EDIT: I hope? Did it work? GitHub is strange.
- My brain is fried now, kek.
[v37 Weapon Comparison.xlsx](https://github.com/NTrixner/RaggedLandsPenAndPaper/files/9390240/v37.Weapon.Comparison.xlsx)

**Comment by NTrixner** [comment]
- [ ] Shouldn't Slings & Slingshots be in the category "throwing weapons"? Minor errors: you can learn "Trowing Training" and Short Spears are in the "thrown" category, instead of "throwing".
_Done_

- [ ] To avoid confusion, I suggest using "You are trained with all (type) weapons" for normal trainings and "You are trained with ONE kind of weapon" for the Weapon Training perk. Also I am 90% certain there is a way to write "If you already have another perk..." only once, lol.
_Added the "one" with example to simple weapon training. The "all" is already in the perks, just in the line regarding the descriptor. Added the "If you already have another perk" into the heading for martial trainings. This was also a good place to explain the bonus with Over/Under and multiple armor training perks_

- [ ] Tough one here: Are "Draw & Sheathe" interesting design spaces? Is it fun to play around? Is it worth writing it down (and remembering) it for every single one, or shouldn't they just depend on weapon size for example (S= 2s, M=3s, L=4s)? With maybe exceptions for Daggers & Bows?
_I've thought about this for a while, but honestly I think it adds to the game on the grounds of surprise, preparedness and their relation to the type of character you play. But you're right that a simplification would be a good idea. _

- [ ] Are descriptors like "Simple" and "Regular" necessary, if weapons already are collected in a list with that name? 
_Since every weapon is it's own file in the code, I'd still like to add them, to make sure the file can be reused in other lists._

- [ ] Are the "melee/ranged" descriptors used somewhere, and/or can they not reliably be concluded from the attack ranges?
_For the current weapons they might seem redundant, but I don't want to rework everything later when we add a 3 passus ranged weapon at some point. Additionally, they will be used in perks later. Melee attacks are used already - see Brutal Attack_

- [ ] Speaking of which: Should the "one/two handed" descriptors be part of the weapon maneuvers?
_I've thought about it, but for now I'm gonna leave it as is. Maybe if we want to bring in more variety later, we might change it.
For now this really only is interesting for loading weapons anyway_

- [ ] Is the ability to knock out enemies strictly a "blunt damage" thing, rather than a weapon type thing?
_Again, a thing for the future - I don't want to restrict myself by making this a blanket blunt damage thing. Might add something like blowdarts with sleep poison or something later, and then have to rewrite everything again. Also, having it as a specific thing and not just a general rule, makes it more obvious to the player_

- [ ] Is there a fixed system behind cutting, blunt and piercing? Because it ain't alphabetical, lol.
_no fixed system. but might add as a ticket for later, similar to pronouns and number format imho_

- [ ] Bearded Axe & Battle Axe feel too similar. As do Riding Bow & Bow. I know it's a design document and there are things to be said for number of dice etc, but I'd rather have clearer niches than overwhelming options.
_I'll keep them in for now - maybe once I actually make a "PHB" type document, I'll restrict the options_

- [ ] "Has to be reloaded before every shot" makes it unclear whether a "re"load needs to happen before the first shot. Should it not be "loading"?"
_Done_

- [ ] Reloading can be done as part of the shoot action" is equally confusing, as it sounds like the AP cost is covered, but I suppose it's more about the 1 action limitation per turn? Maybe use "in conjunction"? Or force it into one maneuver?
_changed the formulation to "Loading can be done before the Shoot action, counting together as only one static action, while adding their AP costs together." Let's not make it ambiguous._

- [ ] Mace & Morning Star have an odd damage calculation. Not only is the blunt damage missing, but the way rounding works in your system; 2x 1/2 ST is often more than ST. It's most likely not op tho, as it interacts unfavourably with armor, and carves this an interesting non-armor crushing niche.
_yeah, blunt was missing. Done. Other than that, I'm fine with the rounding here, I want to reward players for taking a "weaker" weapon in favor of versatility_

- [ ] Are Great Swords and Lances supposed to be One-Handed? 
_Done for Great Sword. Lances are one-handed, yes_

- [ ] Is a Morning Star really a Two-Handed Mace?
_Yes, in this context it is. There's a whole bunch of different things that could be considered a morning star in history. For example, what we call a mace could also be called a morningstar in some circumstances, while other morningstars might be more akin to flails. We could rename it, but then I'd call it a Heavy Mace or something like that_

- [ ] Are Guisarmes not Polearms? 
_They are theoretically, but they require unusual weapon training. That's why they lack the descriptor. We could add the descriptor, and add "non-usual" to the weapon training perks_
 
- [ ] Are Hand Crossbows their own "Hand Crossbow" category (as the descriptor implies) or Crossbows as well? Because the latter needs 710 CP to learn as an "unusual weapon", but only 110 CP as a package with all Crossbows.
_They are their own category, for the same reason as guisarmes_

**Comment by NTrixner** [comment]
On the other hand, regarding the Mace and Morningstar thing - most images I find of Maces are actually just sticks with balls on them (pure blunt), or have more blade-like attachments (which I thought about anyways, giving it Blunt and Cutting)
We could divide these into Mace and Heavy Mace, giving Blunt and Cutting; and Morningstar and Heavy Morningstar, giving Blunt and Piercing. What do you think?

**Comment by NTrixner** [comment]
For now I opened these followup issues:
https://github.com/NTrixner/RaggedLandsPenAndPaper/issues/234
https://github.com/NTrixner/RaggedLandsPenAndPaper/issues/235
https://github.com/NTrixner/RaggedLandsPenAndPaper/issues/236
https://github.com/NTrixner/RaggedLandsPenAndPaper/issues/237

**Comment by Hexopus** [comment]
I have no history degree either, lol (and I am neither Max nor Leo enough to fight about historical accuracy in a fantasy game), but that sounds at least mechanically interesting :D--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 19.09.22, 21:26 schrieb Nikolaus Trixner ***@***.***>:

   
  On the other hand, regarding the Mace and Morningstar thing - most images I find of Maces are actually just sticks with balls on them (pure blunt), or have more blade-like attachments (which I thought about anyways, giving it Blunt and Cutting) We could divide these into Mace and Heavy Mace, giving Blunt and Cutting; and Morningstar and Heavy Morningstar, giving Blunt and Piercing. What do you think?
